apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2017-07-12T18:15:18Z
  generation: 1
  labels:
    k8s-app: influxdb
    task: monitoring
  name: monitoring-influxdb
  namespace: kube-system
  resourceVersion: "21852818"
  selfLink: /apis/extensions/v1beta1/namespaces/kube-system/deployments/monitoring-influxdb
  uid: 0f78a057-672e-11e7-8683-02cc7a251390
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: influxdb
      task: monitoring
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: influxdb
        task: monitoring
    spec:
      containers:
      - image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
        imagePullPolicy: IfNotPresent
        name: influxdb
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      serviceAccount: io-rancher-system
      serviceAccountName: io-rancher-system
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: influxdb-storage
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2017-07-12T18:15:18Z
    lastUpdateTime: 2017-07-12T18:15:18Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  replicas: 1
  updatedReplicas: 1
