apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
  - name: api
    port: 9200
    targetPort: 9200
  - name: clients
    port: 9300
    targetPort: 9300
  selector:
    app: elasticsearch
