apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs"
  labels:
    component: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
