apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-data
  labels:
    component: elasticsearch
    role: data
spec:
  replicas: 3
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: elasticsearch
        role: data
    spec:
      containers:
      - name: es-data
        args:
        - elasticsearch
        - -Des.cluster.name=graylog
        - -Des.multicast.enabled=false
        - -Des.discovery.zen.ping.unicast.hosts=elasticsearch
        - -Des.discovery.zen.minimum_master_nodes=1
        - -Des.network.host=_non_loopback:ipv4_
        - -Des.node.data=true
        - -Des.node.master=false
        image: elasticsearch:2.3
        ports:
        - name: api
          containerPort: 9200
        - name: clients
          containerPort: 9300
        resources:
          requests:
            cpu: "100m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "3Gi"
      restartPolicy: Always
