kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker
  labels:
    component: spark
    role: worker
spec:
  replicas: 2
  selector:
    component: spark
    role: worker
  template:
    metadata:
      labels:
        component: spark
        role: worker
    spec:
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark:1.5.2_v1
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
