kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-ui-proxy
  labels:
    component: spark
    role: ui-proxy
spec:
  replicas: 1
  selector:
    component: spark
    role: ui-proxy
  template:
    metadata:
      labels:
        component: spark
        role: ui-proxy
    spec:
      containers:
        - name: spark-ui-proxy
          image: elsonrodriguez/spark-ui-proxy:1.0
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
          args:
            - spark-master:8080
          livenessProbe:
              httpGet:
                path: /
                port: 80
              initialDelaySeconds: 120
              timeoutSeconds: 5
