kind: Service
apiVersion: v1
metadata:
  name: spark-ui-proxy
  labels:
    component: spark
    role: ui-proxy
spec:
  # type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    component: spark
    role: ui-proxy
