kind: Service
apiVersion: v1
metadata:
  name: spark-master
  labels:
    component: spark
    role: master
spec:
  ports:
    - port: 7077
      targetPort: 7077
      name: spark
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    component: spark
    role: master
