server:
  ports:
  - 12201:12201/udp
  - 12900:12900/tcp
  - 9000:9000/tcp
  - 5555:5555/udp
  - 12202:12202/udp
  - 12203:12203/tcp
  - 12204:12204/udp
  - 12205:12205/tcp
  - 12206:12206/udp
  - 514:514/tcp
  - 514:514/udp
  environment:
    GRAYLOG_PASSWORD_SECRET: somepasswordpepper
    GRAYLOG_REST_TRANSPORT_URI: http://192.0.0.10:12900
    GRAYLOG_ROOT_PASSWORD_SHA2: 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
  external_links:
  - elasticsearch/slaves:elasticsearch
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: graylog2/server
  links:
  - mongo:mongo
  volumes:
  - /data/graylog/data/journal:/usr/share/graylog/data/journal
  - /data/graylog/config:/usr/share/graylog/data/config
  stdin_open: true
mongo:
  labels:
    io.rancher.container.pull_image: always
  tty: true
  image: mongo
  volumes:
  - /data/db:/data/db
  stdin_open: true
