apiVersion: v1
kind: Service
metadata:
  name: monitoring-grafana
  namespace: kube-system
  annotations:
    io.rahcnar.domain: grafana.dev.wrrr.online
    io.rahcnar.ip: private
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: monitoring-grafana
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    k8s-app: grafana
