apiVersion: v1
kind: Service
metadata:
  name: graphite
  labels:
    component: monitoring
    app: graphite
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    protocol: TCP
    port: 2000
  - name: carbon-rtext
    targetPort: 2003
    protocol: TCP
    port: 2003
  - name: carbon-rpickle
    targetPort: 2004
    protocol: TCP
    port: 2004
  - name: carbon-atext
    targetPort: 2023
    protocol: TCP
    port: 2023
  - name: carbon-apickle
    targetPort: 2024
    protocol: TCP
    port: 2024
  selector:
    component: monitoring
    app: graphite
