apiVersion: v1
kind: Service
metadata:
  name: cerebro
  namespace: logging
  annotations:
    io.rahcnar.domain: cerebro.dev.wrrr.online
    io.rahcnar.ip: private
  labels:
    component: elasticsearch
    role: cerebro
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 9000
    targetPort: 9000
  selector:
    component: elasticsearch
    role: cerebro
