apiVersion: v1
kind: Service
metadata:
  name: kopf
  labels:
    component: elasticsearch
    role: kopf
spec:
  type: LoadBalancer
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    component: elasticsearch
    role: kopf
