kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: efs-provisioner-schedule
  namespace: kube-system
  labels:
    app: storage-provisioner
    storage: efs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storage-provisioner
        storage: efs
        role: client
    spec:
      containers:
        - name: provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v2.0.0
          volumeMounts:
            - name: storage-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: efs-provisioner
            - name: NFS_SERVER
              value: fs-12345678.efs.eu-west-1.amazonaws.com
            - name: NFS_PATH
              value: /
      volumes:
        - name: storage-root
          nfs:
            server: fs-12345678.efs.eu-west-1.amazonaws.com
            path: /
