kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
  labels:
    app: storage-provisioner
    storage: nfs
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: storage-provisioner
        storage: nfs
        role: client
    spec:
      containers:
        - name: provisioner
          image: quay.io/external_storage/nfs-client-provisioner:v2.0.0
          volumeMounts:
            - name: storage-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: nfs-provisioner
            - name: NFS_SERVER
              value: 192.168.0.10
            - name: NFS_PATH
              value: /
      volumes:
        - name: storage-root
          nfs:
            server: 192.168.0.10
            path: /
