apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-07-12T18:15:14Z
  labels:
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: KubeDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "21851526"
  selfLink: /api/v1/namespaces/kube-system/services/kube-dns
  uid: 0d109e19-672e-11e7-8683-02cc7a251390
spec:
  clusterIP: 10.43.0.10
  ports:
  - name: dns
    port: 53
    protocol: UDP
    targetPort: 53
  - name: dns-tcp
    port: 53
    protocol: TCP
    targetPort: 53
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
