apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2017-07-02T00:15:12Z
  labels:
    app: helm
    name: tiller
  name: tiller-deploy
  namespace: kube-system
  resourceVersion: "20053091"
  selfLink: /api/v1/namespaces/kube-system/services/tiller-deploy
  uid: 84432948-5ebb-11e7-9a7a-02cc7a698fca
spec:
  clusterIP: 10.43.129.59
  ports:
  - name: tiller
    port: 44134
    protocol: TCP
    targetPort: tiller
  selector:
    app: helm
    name: tiller
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
