kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: cerebro
  labels:
    component: elasticsearch
    role: cerebro
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        component: elasticsearch
        role: cerebro
    spec:
      containers:
      - name: cerebro
        image: yannart/cerebro:0.6.4
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: cerebro
  labels:
    component: elasticsearch
    role: cerebro
spec:
  type: LoadBalancer
  selector:
    component: elasticsearch
    role: cerebro
  ports:
  - targetPort: 9000
    port: 8080
