apiVersion: v1
kind: Service
metadata:
  namespace: logging
  labels:
    app: graylog
    tier: elasticsearch
  name: elasticsearch
spec:
  ports:
  - name: api
    port: 9200
    targetPort: 9200
  - name: clients
    port: 9300
    targetPort: 9300
  selector:
    app: graylog
    tier: elasticsearch
