apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: logging
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: graylog
        tier: elasticsearch
        role: master
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:2
        args:
        - elasticsearch
        - -Des.cluster.name=graylog
        volumeMounts:
        - name: elasticsearch-persistent-storage
          mountPath: /usr/share/elasticsearch/data
      restartPolicy: Always
      volumes:
      - name: elasticsearch-persistent-storage
        persistentVolumeClaim:
          claimName: elasticsearch-pv-claim
