apiVersion: v1
kind: Service
metadata:
  namespace: logging
  labels:
    service: mongo
  name: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: graylog
    tier: mongo
    role: master
