apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging
  name: mongo-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-storage"
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging
  name: graylog-config-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-storage"
  labels:
    app: graylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging
  name: graylog-journal-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-storage"
  labels:
    app: graylog
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: logging
  name: elasticsearch-pv-claim
  annotations:
    volume.beta.kubernetes.io/storage-class: "efs-storage"
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
