apiVersion: v1
kind: Service
metadata:
  name: graylog-tcp
  namespace: logging
  labels:
    component: logging
    input: tcp
    app: graylog
spec:
  type: LoadBalancer
  ports:
  - name: logspout
    port: 2514
    protocol: TCP
    targetPort: 2514
  - name: rfc3164
    port: 3514
    protocol: TCP
    targetPort: 3514
  - name: rfc5424
    port: 5514
    protocol: TCP
    targetPort: 5514
  selector:
    component: logging
    app: graylog
