apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: logging
  annotations:
    io.rahcnar.domain: graylog.dev.wrrr.online
    io.rahcnar.ip: private
  labels:
    component: logging
    input: www
    app: graylog
spec:
  type: LoadBalancer
  ports:
  - name: rest
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: www
    port: 80
    protocol: TCP
    targetPort: 9000
  selector:
    component: logging
    app: graylog
