apiVersion: v1
kind: Service
metadata:
  name: jupyter
  labels:
    app: notebook
    component: jupyter
spec:
  ports:
    - port: 80
      targetPort: 8888
      name: jupyter
  selector:
    app: notebook
    component: jupyter
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: notebook
    component: jupyter
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notebook
        component: jupyter
    spec:
      containers:
      - name: jupyter
        image: gallna/jupyter
        ports:
        - containerPort: 8888
          name: jupyter
        command:
        - start-notebook.sh
        args:
        - --NotebookApp.token=''
        resources:
          requests:
            cpu: 100m
