kind: Service
apiVersion: v1
metadata:
  name: zeppelin
  labels:
    app: notebook
    component: zeppelin
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: notebook
    component: zeppelin
  type: LoadBalancer

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zeppelin
  labels:
    app: notebook
    component: zeppelin
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: notebook
        component: zeppelin
    spec:
      containers:
        - name: zeppelin
          image: gcr.io/google_containers/zeppelin:v0.5.6_v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
