telegraf:
  image: telegraf:latest
  ports:
  - 8092:8092/udp
  - 8125:8125/tcp
  - 8094:8094/tcp
  - 8083:8083/tcp
  - 8086:8086/tcp
  environment:
    GRAYLOG_PASSWORD_SECRET: somepasswordpepper
  volumes:
  - ./graylog.conf:/etc/telegraf/telegraf.d/graylog.conf
  - ./telegraf.conf:/etc/telegraf/telegraf.conf
