apiVersion: v1
kind: Service
metadata:
  name: monitoring-influxdb
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: monitoring-influxdb
    task: monitoring
spec:
  type: LoadBalancer
  sessionAffinity: None
  ports:
  - port: 8086
    protocol: TCP
    targetPort: 8086
  selector:
    k8s-app: influxdb
    task: monitoring
